-- ============================================================================
-- Combined migration file — generated by concatenating supabase/migrations/*.sql
-- and supabase/seed.sql, in order, for pasting into the Supabase SQL editor.
--
-- This is a workaround for a CLI bug (SchemaError on inserted_at on the API
-- keys endpoint during `supabase link`), not a replacement for the individual
-- migration files. Never edit this file directly — regenerate it instead.
-- ============================================================================

-- ============================================================================
-- BEGIN: migrations/20260807203000_enums.sql
-- ============================================================================

-- BLUEPRINT §2.2
-- stock_status is intentionally NOT created as a stored enum: the blueprint
-- marks it "derived, not stored" — it's computed from stock_quantity /
-- low_stock_threshold at query time, never persisted as a column.

create extension if not exists pgcrypto;

create type order_status as enum (
  'pending',
  'confirmed',
  'preparing',
  'shipped',
  'completed',
  'cancelled'
);

create type country_code as enum (
  'XK',
  'AL',
  'MK',
  'OTHER'
);

create type admin_role as enum (
  'owner',
  'staff'
);

create type locale as enum (
  'sq',
  'en'
);

-- ============================================================================
-- BEGIN: migrations/20260807203100_categories.sql
-- ============================================================================

-- BLUEPRINT §2.3 categories, category_translations

create table categories (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  image_url text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table category_translations (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references categories (id) on delete cascade,
  locale locale not null,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, locale)
);

-- ============================================================================
-- BEGIN: migrations/20260807203200_products.sql
-- ============================================================================

-- BLUEPRINT §2.3 products, product_translations
-- Money is always INTEGER cents — never numeric, never float.

create table products (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  sku text unique,
  category_id uuid references categories (id) on delete set null,
  price_cents int not null check (price_cents > 0),
  discount_price_cents int check (
    discount_price_cents is null
    or (discount_price_cents > 0 and discount_price_cents < price_cents)
  ),
  stock_quantity int not null default 0 check (stock_quantity >= 0),
  low_stock_threshold int not null default 3,
  track_inventory boolean not null default true,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  sales_count int not null default 0,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table product_translations (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references products (id) on delete cascade,
  locale locale not null,
  name text not null,
  short_description text,
  description text,
  meta_title text,
  meta_description text,
  -- BLUEPRINT §2.5 — 'simple' dictionary on purpose: Postgres has no Albanian
  -- stemmer, and 'english' stemming would mangle Albanian tokens.
  search_vector tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(name, '')), 'A')
    || setweight(to_tsvector('simple', coalesce(short_description, '')), 'B')
    || setweight(to_tsvector('simple', coalesce(description, '')), 'C')
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, locale)
);

-- ============================================================================
-- BEGIN: migrations/20260807203300_product_images.sql
-- ============================================================================

-- BLUEPRINT §2.3 product_images

create table product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references products (id) on delete cascade,
  storage_path text not null,
  alt_sq text,
  alt_en text,
  sort_order int not null default 0,
  width int,
  height int,
  blur_data_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- BEGIN: migrations/20260807203400_shipping_rates.sql
-- ============================================================================

-- BLUEPRINT §2.3 shipping_rates
-- Seeded as data, not a constant, so the seller can change rates without a
-- deploy.

create table shipping_rates (
  id uuid primary key default gen_random_uuid(),
  country country_code unique not null,
  rate_cents int not null,
  free_shipping_threshold_cents int,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- BEGIN: migrations/20260807203500_orders.sql
-- ============================================================================

-- BLUEPRINT §2.3 orders, order_items
-- order_items is an immutable snapshot: product name, slug, image and unit
-- price are copied at purchase time so deleting or editing a product can
-- never mutate order history.

create table orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  public_token uuid unique not null default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  phone text not null,
  phone_country text not null,
  email text,
  address_line text not null,
  city text not null,
  postal_code text,
  country country_code not null,
  customer_note text,
  subtotal_cents int not null,
  shipping_cents int not null,
  total_cents int not null,
  currency text not null default 'EUR',
  status order_status not null default 'pending',
  locale locale not null,
  admin_note text,
  ip_hash text,
  user_agent text,
  confirmed_at timestamptz,
  shipped_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders (id) on delete cascade,
  product_id uuid references products (id) on delete set null,
  product_name_sq text not null,
  product_name_en text not null,
  product_slug text not null,
  image_url text,
  unit_price_cents int not null,
  original_price_cents int,
  quantity int not null check (quantity > 0),
  line_total_cents int not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- BEGIN: migrations/20260807203600_admin_users.sql
-- ============================================================================

-- BLUEPRINT §2.3 admin_users
-- Membership in this table IS the authorisation grant. An auth.users row
-- with no admin_users row has zero access.

create table admin_users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text,
  role admin_role not null default 'staff',
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- BEGIN: migrations/20260807203700_functions_and_triggers.sql
-- ============================================================================

-- BLUEPRINT §2.6, §2.7

-- §2.6 — helper used by RLS policies in the next migration.
create or replace function is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from admin_users
    where id = auth.uid() and is_active = true
  );
$$;

-- §2.7 set_updated_at() — BEFORE UPDATE on all tables.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger categories_set_updated_at
  before update on categories
  for each row execute function set_updated_at();

create trigger category_translations_set_updated_at
  before update on category_translations
  for each row execute function set_updated_at();

create trigger products_set_updated_at
  before update on products
  for each row execute function set_updated_at();

create trigger product_translations_set_updated_at
  before update on product_translations
  for each row execute function set_updated_at();

create trigger product_images_set_updated_at
  before update on product_images
  for each row execute function set_updated_at();

create trigger shipping_rates_set_updated_at
  before update on shipping_rates
  for each row execute function set_updated_at();

create trigger orders_set_updated_at
  before update on orders
  for each row execute function set_updated_at();

create trigger order_items_set_updated_at
  before update on order_items
  for each row execute function set_updated_at();

create trigger admin_users_set_updated_at
  before update on admin_users
  for each row execute function set_updated_at();

-- §2.7 generate_order_number() — BEFORE INSERT on orders, EMB-{YYYY}-{seq}.
create sequence if not exists order_number_seq;

create or replace function generate_order_number()
returns trigger
language plpgsql
as $$
begin
  if new.order_number is null then
    new.order_number := 'EMB-' || to_char(now(), 'YYYY') || '-'
      || lpad(nextval('order_number_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

create trigger orders_generate_order_number
  before insert on orders
  for each row execute function generate_order_number();

-- §2.7 set_status_timestamps() — BEFORE UPDATE on orders; stamps the
-- relevant timestamp column when status changes.
create or replace function set_status_timestamps()
returns trigger
language plpgsql
as $$
begin
  if new.status is distinct from old.status then
    case new.status
      when 'confirmed' then new.confirmed_at := now();
      when 'shipped' then new.shipped_at := now();
      when 'completed' then new.completed_at := now();
      when 'cancelled' then new.cancelled_at := now();
      else null;
    end case;
  end if;
  return new;
end;
$$;

create trigger orders_set_status_timestamps
  before update on orders
  for each row execute function set_status_timestamps();

-- §2.7 decrement_stock(order_id) — called inside the checkout transaction,
-- after order + order_items have been inserted. SELECT ... FOR UPDATE locks
-- each referenced product row before checking/decrementing, so two
-- concurrent checkouts can't both oversell the last unit. Raises if
-- insufficient stock; the transaction is rolled back by the caller.
create or replace function decrement_stock(p_order_id uuid)
returns void
language plpgsql
as $$
declare
  item record;
  current_stock int;
begin
  for item in
    select product_id, quantity
    from order_items
    where order_id = p_order_id
      and product_id is not null
  loop
    select stock_quantity into current_stock
    from products
    where id = item.product_id
      and track_inventory = true
    for update;

    if current_stock is not null then
      if current_stock < item.quantity then
        raise exception 'Insufficient stock for product %', item.product_id
          using errcode = 'P0001';
      end if;

      update products
      set stock_quantity = stock_quantity - item.quantity
      where id = item.product_id;
    end if;
  end loop;
end;
$$;

-- §2.7 increment_sales_count() — AFTER UPDATE on orders when status moves to
-- 'completed'.
create or replace function increment_sales_count()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' then
    update products p
    set sales_count = sales_count + oi.quantity
    from order_items oi
    where oi.order_id = new.id
      and oi.product_id = p.id;
  end if;
  return new;
end;
$$;

create trigger orders_increment_sales_count
  after update on orders
  for each row execute function increment_sales_count();

-- ============================================================================
-- BEGIN: migrations/20260807203800_rls_policies.sql
-- ============================================================================

-- BLUEPRINT §2.6
-- RLS is enabled on every table. service_role bypasses RLS by default on
-- Supabase, so no explicit service_role policies are written here.
--
-- orders and order_items get NO anon policy at all, not even insert — the
-- absence of any policy for a role means that role has zero access once RLS
-- is enabled. Orders are created only through a server action using the
-- service role.

alter table categories enable row level security;
alter table category_translations enable row level security;
alter table products enable row level security;
alter table product_translations enable row level security;
alter table product_images enable row level security;
alter table shipping_rates enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table admin_users enable row level security;

-- categories / category_translations
-- anon: SELECT where is_active · authenticated admin: SELECT all

create policy categories_anon_select
  on categories for select
  to anon
  using (is_active);

create policy categories_admin_select
  on categories for select
  to authenticated
  using (is_admin());

create policy category_translations_anon_select
  on category_translations for select
  to anon
  using (
    exists (
      select 1 from categories c
      where c.id = category_translations.category_id
        and c.is_active
    )
  );

create policy category_translations_admin_select
  on category_translations for select
  to authenticated
  using (is_admin());

-- products / product_translations / product_images
-- anon: SELECT where is_active AND deleted_at IS NULL · authenticated admin: SELECT all

create policy products_anon_select
  on products for select
  to anon
  using (is_active and deleted_at is null);

create policy products_admin_select
  on products for select
  to authenticated
  using (is_admin());

create policy product_translations_anon_select
  on product_translations for select
  to anon
  using (
    exists (
      select 1 from products p
      where p.id = product_translations.product_id
        and p.is_active
        and p.deleted_at is null
    )
  );

create policy product_translations_admin_select
  on product_translations for select
  to authenticated
  using (is_admin());

create policy product_images_anon_select
  on product_images for select
  to anon
  using (
    exists (
      select 1 from products p
      where p.id = product_images.product_id
        and p.is_active
        and p.deleted_at is null
    )
  );

create policy product_images_admin_select
  on product_images for select
  to authenticated
  using (is_admin());

-- shipping_rates
-- anon: SELECT where is_active · authenticated admin: SELECT all

create policy shipping_rates_anon_select
  on shipping_rates for select
  to anon
  using (is_active);

create policy shipping_rates_admin_select
  on shipping_rates for select
  to authenticated
  using (is_admin());

-- orders / order_items
-- anon: none · authenticated admin: SELECT/UPDATE if is_admin()

create policy orders_admin_select
  on orders for select
  to authenticated
  using (is_admin());

create policy orders_admin_update
  on orders for update
  to authenticated
  using (is_admin())
  with check (is_admin());

create policy order_items_admin_select
  on order_items for select
  to authenticated
  using (is_admin());

create policy order_items_admin_update
  on order_items for update
  to authenticated
  using (is_admin())
  with check (is_admin());

-- admin_users
-- anon: none · authenticated admin: SELECT own row only

create policy admin_users_select_own
  on admin_users for select
  to authenticated
  using (id = auth.uid());

-- ============================================================================
-- BEGIN: migrations/20260807203900_indexes.sql
-- ============================================================================

-- BLUEPRINT §2.3, §2.5

-- products
create index products_category_id_idx
  on products (category_id)
  where deleted_at is null;

create index products_featured_idx
  on products (is_featured)
  where is_active and deleted_at is null;

create index products_sales_count_idx
  on products (sales_count desc);

create index products_created_at_idx
  on products (created_at desc);

-- orders
create index orders_status_created_at_idx
  on orders (status, created_at desc);

create index orders_created_at_idx
  on orders (created_at desc);

create index orders_phone_idx
  on orders (phone);

-- §2.5 search — diacritic-insensitivity matters: Albanian users frequently
-- type "e" for "ë" and "c" for "ç". A generated, unaccent-normalised column
-- is searched alongside the original so both spellings match.
create extension if not exists unaccent;
create extension if not exists pg_trgm;

-- unaccent() is STABLE, not IMMUTABLE, so it can't be used directly inside a
-- GENERATED column. This wrapper pins it to the default text search config
-- and is safe to mark IMMUTABLE.
create or replace function immutable_unaccent(text)
returns text
language sql
immutable
parallel safe
as $$
  select unaccent('unaccent', $1);
$$;

alter table product_translations
  add column name_unaccented text generated always as (
    immutable_unaccent(name)
  ) stored;

create index product_translations_search_vector_idx
  on product_translations using gin (search_vector);

create index product_translations_name_trgm_idx
  on product_translations using gin (name gin_trgm_ops);

create index product_translations_name_unaccented_trgm_idx
  on product_translations using gin (name_unaccented gin_trgm_ops);

-- ============================================================================
-- BEGIN: migrations/20260807204000_effective_price.sql
-- ============================================================================

-- Adds a generated column so price sorting/filtering can use the price the
-- customer actually pays (discount price when set, otherwise base price)
-- directly in the database. PostgREST's query builder can only order/filter
-- by real columns, not a computed COALESCE(discount_price_cents, price_cents)
-- expression, so this is required for correct effective-price sort.

alter table products
  add column effective_price_cents int generated always as (
    coalesce(discount_price_cents, price_cents)
  ) stored;

create index products_effective_price_cents_idx
  on products (effective_price_cents);

-- ============================================================================
-- BEGIN: seed.sql
-- ============================================================================

-- BLUEPRINT §2.3 — shipping rates and category seed data.

insert into shipping_rates (country, rate_cents) values
  ('XK', 200),
  ('AL', 500),
  ('MK', 500),
  ('OTHER', 500);

insert into categories (slug, sort_order) values
  ('cases', 1),
  ('covers', 2),
  ('chargers', 3),
  ('cleaning-tools', 4),
  ('lanyards', 5),
  ('holders', 6);

insert into category_translations (category_id, locale, name)
select c.id, 'sq', v.name_sq
from categories c
join (values
  ('cases', 'Çanta'),
  ('covers', 'Mbulesa'),
  ('chargers', 'Karikues'),
  ('cleaning-tools', 'Vegla pastrimi'),
  ('lanyards', 'Rripa mbajtës'),
  ('holders', 'Mbajtëse')
) as v (slug, name_sq) on v.slug = c.slug;

insert into category_translations (category_id, locale, name)
select c.id, 'en', v.name_en
from categories c
join (values
  ('cases', 'Cases'),
  ('covers', 'Covers'),
  ('chargers', 'Chargers'),
  ('cleaning-tools', 'Cleaning tools'),
  ('lanyards', 'Lanyards'),
  ('holders', 'Holders')
) as v (slug, name_en) on v.slug = c.slug;
